In [9]:
import pandas as pd

from src.data_loader import load_dataset
from src.cleaner import DataCleaner

In [10]:
df = load_dataset("../data/raw/titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
cleaner = DataCleaner(df)

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
cleaner.fill_missing_mean()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [14]:
clean_df = cleaner.get_clean_data()

clean_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
cleaner = DataCleaner(df)

cleaner.fill_missing_mode()

cleaner.get_clean_data().isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [16]:
cleaner = DataCleaner(df)

print("Before:", len(cleaner.df))

cleaner.remove_duplicates()

print("After :", len(cleaner.get_clean_data()))

Before: 891
After : 891

In [17]:
cleaner = DataCleaner(df)

cleaner.drop_columns(["Cabin"])

cleaner.get_clean_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [18]:
cleaner = DataCleaner(df)

cleaner.fill_missing_mode()

cleaner.encode_categorical()

cleaner.get_clean_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,47,2
1,2,1,1,190,0,38.0,1,0,596,71.2833,81,0
2,3,1,3,353,0,26.0,0,0,669,7.9250,47,2
3,4,1,1,272,0,35.0,1,0,49,53.1000,55,2
4,5,0,3,15,1,35.0,0,0,472,8.0500,47,2

In [19]:
cleaner = DataCleaner(df)

cleaner.fill_missing_mean()

cleaner.encode_categorical()

cleaner.minmax_scale()

cleaner.get_clean_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0.000000,0.0,1.0,0.121348,1.0,0.271174,0.125,0.0,0.769118,0.014151,1.00000,0.666667
1,0.001124,1.0,0.0,0.213483,0.0,0.472229,0.125,0.0,0.876471,0.139136,0.55102,0.000000
2,0.002247,1.0,1.0,0.396629,0.0,0.321438,0.000,0.0,0.983824,0.015469,1.00000,0.666667
3,0.003371,1.0,0.0,0.305618,0.0,0.434531,0.125,0.0,0.072059,0.103644,0.37415,0.666667
4,0.004494,0.0,1.0,0.016854,1.0,0.434531,0.000,0.0,0.694118,0.015713,1.00000,0.666667

In [20]:
cleaner = DataCleaner(df)

cleaner.fill_missing_mean()

cleaner.encode_categorical()

cleaner.standardize_numeric()

cleaner.get_clean_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,-1.730108,-0.789272,0.827377,-1.310217,0.737695,-0.592481,0.432793,-0.473674,0.918966,-0.502445,0.451502,0.581114
1,-1.726220,1.266990,-1.566107,-0.991410,-1.355574,0.638789,0.432793,-0.473674,1.282625,0.786845,-1.381627,-1.938460
2,-1.722332,1.266990,0.827377,-0.357685,-1.355574,-0.284663,-0.474545,-0.473674,1.646283,-0.488854,0.451502,0.581114
3,-1.718444,1.266990,-1.566107,-0.672604,-1.355574,0.407926,0.432793,-0.473674,-1.442322,0.420730,-2.103768,0.581114
4,-1.714556,-0.789272,0.827377,-1.671790,0.737695,0.407926,-0.474545,-0.473674,0.664904,-0.486337,0.451502,0.581114